### ISSUE TITLE
Pybind11 fails with undefined symbol

### ISSUE THREAD

**Issue by yuey1203** [shakfu/py_cpp_wrap#1]
Hi I was trying to use this code as starter for python wrapping for hola, but when I try to import hola, it fails with an error `undefined symbol`. This only seems to happen for libdialect, so I was wondering if this is a previously found issue during your tests, and if so, how to solve this.

**Comment by shakfu** [comment]
Sorry, this repo is more of a record of my experiments in wrapping. They may contain bugs because it's just a snapshot of an experiment at the time.

Incidentally, I've actually wrapped hola in a separate project already: https://github.com/shakfu/pyhola

Check that out and let me know how that go on that repo if needed

**Comment by yuey1203** [comment]
Awesome! I will check it out!
